server:
  port: 8090
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 114.132.226.23:8848 # nacos地址
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:7529
          predicates:
            - Path=/api/**
      globalcors: # 全局的跨域处理
              add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
              corsConfigurations:
                '[/**]':
                  allowedOrigins: "*" # 允许哪些网站的跨域请求
                  allowedMethods: "*" #允许的跨域ajax的请求方式
                  allowedHeaders: "*" # 允许在请求中携带的头信息
                  allowCredentials: true # 是否允许携带cookie
                  maxAge: 360000 # 这次跨域检测的有效期